### ISSUE TITLE
Resolve intermitent CI failure

### ISSUE THREAD

**Issue by evolve2k** [koalagator/koalagator#31]
TLDR: Replace Selenium with Cupright
Cupright is native ruby.

Should resolve the intermittent CI build failures around selenium.
https://github.com/rubycdp/cuprite

eg. 
  1) Administrative suite is hidden behind authorization Un-authorized users are not permitted in /changes
     Failure/Error: expect([403]).to include page.status_code

     Capybara::NotSupportedByDriverError:
       Capybara::Driver::Base#status_code
     # ./spec/features/admin_auth_spec.rb:29:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:152:in `block (2 levels) in <top (required)>'

**Comment by evolve2k** [comment]
Replaced selenium with cuprite (native ruby) in https://github.com/koalagator/koalagator/pull/35.
Expect this to resolve this issue. Open a new issue if CI contuninues to fail intermitently.
